#!/usr/bin/perl -w

# for pcap to RabbitMQ
# written by Daniel Guerra
# initializes RabbitMQ

BEGIN {
        unshift(@INC,'/usr/local/lib/x86_64-linux-gnu/perl/5.20.2');
}

# libs
use strict;
use Net::AMQP::RabbitMQ;

# global var
my $mq;

# check the input first
my $args=@ARGV;
if ($args < 5)
{
		print STDERR ("Usage: $0 <amqp ip/dnsname> <user> <pass> <exchange> <routingkey>\n");
		exit(0);
}
my $ip=$ARGV[0];
my $user=$ARGV[1];
my $pass=$ARGV[2];
my $exchange=$ARGV[3];
my $key=$ARGV[4];
my $queuename=$exchange."-".$key;

#connect to rabbitmq
$mq = Net::AMQP::RabbitMQ->new();
$mq->connect($ip, { user => $user, password => $pass });
$mq->channel_open(1);
$mq->exchange_declare(1,$exchange);
$mq->queue_declare(1, $queuename);
$mq->queue_bind(1, $queuename, $exchange, $key);

# finish
$mq->channel_close(1);
$mq->disconnect();
